//This code defines a Java class that represents a teacher entity in the application. The purpose of this class is to provide a model for storing and retrieving teacher data from a database, and to provide methods for manipulating this data.
//The purpose of this class is to provide a model for a teacher entity that can be stored and retrieved from a database.

package com.example.les12services.model;

import jakarta.persistence.*;

import java.time.LocalDate;

//The @Entity annotation on the class specifies that this class is a JPA entity, which means it is mapped to a database table.
@Entity
//The @Table(name = "teachers") annotation specifies the name of the database table that this entity is mapped to.
@Table(name = "teachers")
public class Teacher {
    //The class includes instance variables for the ID, first name, last name, date of birth, and salary of a teacher.
    //The @Id annotation on the id field specifies that this field is the primary key for the entity.
    //The @GeneratedValue annotation on the id field specifies that the value of this field will be automatically generated by the database.
    @Id
    @GeneratedValue
    private Long id;
    private String firstName;
    //The @Column(length = 3) annotation on the lastName field specifies that the length of the string must be no more than 3 characters.
    @Column(length = 3)
    private String lastName;
    private LocalDate dob;
    private int salary;

    //The class includes getter and setter methods for each of the instance variables, which are used to retrieve and set the values of these variables.
    //The methods defined in this class provide a way to manipulate the data in a teacher entity and to interact with other parts of the application.
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {return firstName;}
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public LocalDate getDob() {
        return dob;
    }
    public void setDob(LocalDate dob) {
        this.dob = dob;
    }

    public int getSalary() {
        return salary;
    }
    public void setSalary(int salary) {
        this.salary = salary;
    }

}
